replicaCount: 1
name: nginxdemo
image:
  repository: abhishekjaindevops/docker-demo
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8080
  internalPort: 8080
ingress:
  enabled: false
  annotations:
    ingress.kubernetes.io/ssl-redirect: 'true'
    kubernetes.io/tls-acme: 'true'
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx-internal
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: nginxdemo.in
      paths:
        - /
  tls:
    - secretName: nginxdemo
      hosts:
        - nginxdemo.in
resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi
