{{- if .Values.secrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: {{ .Release.Name }}-secret
spec:
  encryptedData:
    {{- range $key, $val := .Values.secrets }}
    {{ $key }}: {{ $val }}
    {{- end }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: {{ .Release.Name }}-secret
{{- end }}
